### ISSUE TITLE
SPI for 2MB version

### ISSUE THREAD

**Issue by Kebehsenuef** [melsem/openwrt-19.07.7-spi#2]
Hello
Thanks for your work. I have a OPi Zero 2MB SPI version. Is it possible to install the image on it. Is it possible to use WiFi on the SD version?
MfG Steve

**Comment by melsem** [comment]
Yes, Opangepi-zero has 2MB of flash memory.
And it needs to be re-soldered for 16 MB.

Yes, you can use WiFi on the SD version.
But there will be no more than 10MBit speed on wifi.
Test images for MMC ext4-sdcard.img.gz to [orangepi-r1, orangepi-zero, orangepi-zero-lts,
orangepi-pc.](https://github.com/melsem/openwrt-19.07.7-spi/tree/master/images)

**Comment by Kebehsenuef** [comment]
Thanks for the image.
the limitation does not bother, there are only ESP32 in the network 
Does the limitation also apply to the SPI version?
What happens if I use an EMMC with an SD adapter?

**Comment by melsem** [comment]
> Does the limitation also apply to the SPI version?

This is a limitation of the WIFI driver.
xr819 is a bad chip.
