### ISSUE TITLE
Orange Pi Zero LTS - firmware write "Failed to erase block"

### ISSUE THREAD

**Issue by xyzroe** [melsem/openwrt-19.07.7-spi#4]
Hi. 
Thanks for great work. 👍 

I have an error in the process of writing firmware to SPI, maybe you could help me to solve it.

Hardware:
- Orange Pi Zero LTS 512 MB
- Onboard SPI chip MX25L1606E - 16 MB

Software:
- Main image - https://downloads.openwrt.org/releases/19.07.7/targets/sunxi/cortexa7/openwrt-19.07.7-sunxi-cortexa7-sun8i-h2-plus-orangepi-zero-ext4-sdcard.img.gz
- dtb file - https://github.com/melsem/openwrt-19.07.7-spi/blob/master/sun8i-h2-plus-orangepi-zero-lts-dtb
- uboot file - https://github.com/melsem/openwrt-19.07.7-spi/blob/master/sun8i-h2-plus_orangepi-zero-lts-boot.bin
- firmare file - https://github.com/melsem/openwrt-19.07.7-spi/blob/master/sun8i-h2-plus-orangepi-zero-lts-squashfs-sysupgrade.bin

What I did:
1. Flash image on SD card. Replaced original dtb file with your's. Also put mkdir on SD, and put here dt, uboot, firmware files.
2. Boot from SD successfully. Mount SD card, copy 3 files to /tmp folder.
3. Change work directory to /tmp and run
```
mtd -e uboot write sun8i-h2-plus_orangepi-zero-lts-boot.bin uboot
mtd -e dtb write sun8i-h2-plus-orangepi-zero-lts-dtb dtb
mtd -e firmware write sun8i-h2-plus-orangepi-zero-lts-squashfs-sysupgrade.bin firmware
```
uboot and dtb finishing with no errors, but firmware always returns `[e]Failed to erase block.`

I tried to erase the firmware separately `mtd erase firmware` - there are no errors. But when I try to write - I get erase block error.
When I try to boot it seems that device in something like recovery mode, - network LEDs acts, but no IP address at all.

I have also tried using the files from the classic Orange Pi Zero as described on the main repository page. I did not get success, which is expected. 😁

Logs:
```
root@OpenWrt:/tmp# mtd -e uboot write sun8i-h2-plus_orangepi-zero-lts-boot.bin uboot
Unlocking uboot ...
Erasing uboot ...
Writing from sun8i-h2-plus_orangepi-zero-lts-boot.bin to uboot ...     

root@OpenWrt:/tmp# mtd -e dtb write sun8i-h2-plus-orangepi-zero-lts-dtb dtb
Unlocking dtb ...
Erasing dtb ...
Writing from sun8i-h2-plus-orangepi-zero-lts-dtb to dtb ...     

root@OpenWrt:/tmp# mtd -e firmware write sun8i-h2-plus-orangepi-zero-lts-squashfs-sysupgrade.bin firmware
Unlocking firmware ...
Erasing firmware ...
Writing from sun8i-h2-plus-orangepi-zero-lts-squashfs-sysupgrade.bin to firmware ...  [e]Failed to erase block
```

```
root@OpenWrt:/tmp# cat /proc/mtd 
dev:    size   erasesize  name
mtd0: 00080000 00010000 "uboot"
mtd1: 00010000 00010000 "dtb"
mtd2: 00170000 00010000 "firmware"
```

```
root@OpenWrt:/tmp# ls -l
-rw-r--r--    1 root     root             4 Feb 15 15:22 TZ
-rw-r--r--    1 root     root           173 Jan  1  1970 board.json
-rw-r--r--    1 root     root            69 Feb 15 15:23 dhcp.leases
drwxr-xr-x    2 root     root            40 Feb 15 15:22 dnsmasq.d
drwxr-xr-x    3 root     root            80 Feb 15 15:22 etc
drwxr-xr-x    2 root     root            60 Feb 15 15:22 hosts
drwxr-xr-x    3 root     root            60 Feb 15 15:22 lib
drwxr-xr-x    2 root     root           380 Feb 15 15:33 lock
drwxr-xr-x    2 root     root            80 Feb 15 15:22 log
-rw-r--r--    1 root     root            32 Feb 15 15:22 resolv.conf
-rw-r--r--    1 root     root             0 Feb 15 15:22 resolv.conf.auto
drwxr-xr-x    4 root     root           220 Feb 15 15:23 run
drwxrwxrwt    2 root     root            40 Jan  1  1970 shm
drwxr-xr-x    2 root     root            60 Feb 15 15:22 state
-rwxr-xr-x    1 root     root         24576 Feb 15 15:23 sun8i-h2-plus-orangepi-zero-lts-dtb
-rwxr-xr-x    1 root     root      15286546 Feb 15 15:23 sun8i-h2-plus-orangepi-zero-lts-squashfs-sysupgrade.bin
-rwxr-xr-x    1 root     root        475136 Feb 15 15:23 sun8i-h2-plus_orangepi-zero-lts-boot.bin
drwxr-xr-x    2 root     root            80 Jan  1  1970 sysinfo
drwxr-xr-x    2 root     root            40 Feb 15 15:22 tmp
```

Tried twice. Files reloaded and overwritten.

What am I doing wrong?

**Comment by xyzroe** [comment]
Also tried [19.07.2-spi](https://github.com/melsem/openwrt-19.07.7-spi/commit/48e0031242180389e85f5e39b8b530ba72ae5749) using corresponding files. Get the same error. Tried 
zero-lts, r1, and zero. No luck.

**Comment by xyzroe** [comment]
I think my mistake is thinking that onboard SPI chip MX25L1606E has 16 MB.
I had connected to UART, and inside u-boot ran  => sf probe with result
`SF: Detected mx25l1606e with page size 256 Bytes, erase size 4 KiB, total 2 MiB`

**Comment by xyzroe** [comment]
After installing W25Q128FVSIG all work as expected. 
Thanks a lot for your great work.

**Comment by melsem** [comment]
SPI chip MX25L1606E - 2 MB
